// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Suggests relevant beauty services based on an uploaded customer image.
 *
 * - suggestServices - A function that takes an image and returns service suggestions.
 * - SuggestServicesInput - The input type for the suggestServices function.
 * - SuggestServicesOutput - The return type for the suggestServices function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestServicesInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo of the customer’s face, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.' 
    ),
});
export type SuggestServicesInput = z.infer<typeof SuggestServicesInputSchema>;

const SuggestServicesOutputSchema = z.object({
  serviceSuggestion: z
    .string()
    .describe('The beauty service that is most appropriate for the customer.'),
});
export type SuggestServicesOutput = z.infer<typeof SuggestServicesOutputSchema>;

export async function suggestServices(input: SuggestServicesInput): Promise<SuggestServicesOutput> {
  return suggestServicesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestServicesPrompt',
  input: {schema: SuggestServicesInputSchema},
  output: {schema: SuggestServicesOutputSchema},
  prompt: `You are an AI beauty consultant. A customer will upload a picture of their face, and you will suggest the single most appropriate beauty service for them from the list below. Respond with only the service name.

Eyelash Extensions
Lash Lifting
Eyebrow Design

Here is the customer's face: {{media url=photoDataUri}}`,
});

const suggestServicesFlow = ai.defineFlow(
  {
    name: 'suggestServicesFlow',
    inputSchema: SuggestServicesInputSchema,
    outputSchema: SuggestServicesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
