// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Sugere serviços de beleza relevantes com base em uma imagem enviada pelo cliente.
 *
 * - suggestServices - Uma função que recebe uma imagem e retorna sugestões de serviço.
 * - SuggestServicesInput - O tipo de entrada para a função suggestServices.
 * - SuggestServicesOutput - O tipo de retorno para a função suggestServices.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestServicesInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'Uma foto do rosto do cliente, como um URI de dados que deve incluir um tipo MIME e usar codificação Base64. Formato esperado: \'data:<mimetype>;base64,<encoded_data>\'.' 
    ),
});
export type SuggestServicesInput = z.infer<typeof SuggestServicesInputSchema>;

const SuggestServicesOutputSchema = z.object({
  serviceSuggestion: z
    .string()
    .describe('O serviço de beleza mais apropriado para o cliente.'),
});
export type SuggestServicesOutput = z.infer<typeof SuggestServicesOutputSchema>;

export async function suggestServices(input: SuggestServicesInput): Promise<SuggestServicesOutput> {
  return suggestServicesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestServicesPrompt',
  input: {schema: SuggestServicesInputSchema},
  output: {schema: SuggestServicesOutputSchema},
  prompt: `Você é um consultor de beleza de IA. Um cliente fará o upload de uma foto do rosto e você sugerirá o serviço de beleza mais apropriado para ele na lista abaixo. Responda apenas com o nome do serviço.

Extensão de Cílios
Lash Lifting
Design de Sobrancelhas

Aqui está o rosto do cliente: {{media url=photoDataUri}}`,
});

const suggestServicesFlow = ai.defineFlow(
  {
    name: 'suggestServicesFlow',
    inputSchema: SuggestServicesInputSchema,
    outputSchema: SuggestServicesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
